spring:
  datasource:
    url: jdbc:mysql://43.138.195.177:3306/blog_management_system?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wsadBABA168!

mybatis-plus:
  type-aliases-package: com.xx.pojo